version: '3.5'
services:

  php:
    container_name: corp-integrations-php
    build: ./docker/php
    ports:
      - "8002:8000"
    volumes:
      - ./src:/var/www/html
      - ./logs/php:/var/log/php
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Для Linux/WSL
    depends_on:
      - redis
    networks:
      - app_network

  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./src:/var/www/html
  #     # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - php    

  composer:
    image: composer:latest
    container_name: corp-integrations-composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    command: sh -c "composer install && tail -f /dev/null"
    tty: true

  redis:
    image: redis:alpine
    container_name: corp-integrations-redis
    ports:
      # - "6379:6379"
      - "6380:${REDIS_PORT}"
    volumes:
      - ./volumes/redis:/data
    restart: always
    networks:
      - app_network

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: corp-integrations-redis-insight
    ports:
      - "8050:8001" # http://localhost:8001)
    volumes:
      - ./volumes/redis-insight:/db
    restart: always
    depends_on:
      - redis
    networks:
      - app_network
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

  mysql:
    container_name: corp-integrations-mysql
    image: mysql:8.0.19
    ports:
      # - "3306:3306"
      - "3316:${MYSQL_PORT}"
    volumes:
      - ./volumes/mysql8:/var/lib/mysql
    networks:
      - app_network
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  phpmyadmin:
    container_name: corp-integrations-phpmyadmin
    image: phpmyadmin/phpmyadmin # https://hub.docker.com/_/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=${MYSQL_PORT}
      - PMA_ARBITRARY=0
    ports:
      # - "8091:80"
      - "8102:80" # http://localhost:8102/
    networks:
      - app_network
    depends_on:
      - mysql
    restart: unless-stopped

networks:
  app_network:
    driver: bridge